# Generated by Django 2.2.10 on 2020-05-02 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(upload_to='images/Article'),
        ),
        migrations.AlterField(
            model_name='categoriearticle',
            name='image',
            field=models.ImageField(upload_to='images/Categorie'),
        ),
    ]
